# Generated by Django 2.2.7 on 2020-08-08 06:10

from django.db import migrations, models
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(help_text='image landscape size 400px * 200px', upload_to='biographies')),
                ('url_target', models.CharField(blank=True, max_length=256)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, default='')),
                ('description', markdownx.models.MarkdownxField(blank=True, default='', help_text='description using markdown writing')),
                ('created', models.DateTimeField(default=django.utils.timezone.localtime)),
            ],
        ),
    ]
