# Generated by Django 2.2.7 on 2020-08-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biographies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g: Education', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('biographies', models.ManyToManyField(related_name='tags', to='biographies.Biography')),
            ],
        ),
    ]
